### ISSUE TITLE
neoforge issue with cycle

### ISSUE THREAD

**Issue by VaporeonScripts** [Potion-Studios/Oh-The-Biomes-Weve-Gone#127] opened 2024-09-24 16:31 UTC
https://mclo.gs/kR8hunQ

**Comment by VaporeonScripts** [comment] 2024-09-24 16:39
as a temp fix im back at using 2.0.4 till it gets patched

**Comment by JT122406** [comment] 2024-09-24 17:24
Duplicate of #126

**Closed as not planned by JT122406** 2024-09-24 17:24 UTC
Labels: duplicate
