### ISSUE TITLE
Incompatible with Abnormals Mods (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by PercyJames** [Potion-Studios/Oh-The-Biomes-Weve-Gone#51] opened 2024-08-02 00:17 UTC
https://pastebin.com/QrXPsh61

**Comment by CorgiTaco** [comment] 2024-08-11 12:17
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by Apollounknowndev** [comment] 2024-08-11 20:32
Duplicate of #6, it's actually Excessive Building causing the error looking in the crash report.

**Comment by JT122406** [comment] 2024-08-11 21:20
Follow on #6

**Closed by JT122406** 2024-08-11 21:20 UTC
Labels: Incompatibility, Low Priority, Feature Cycle
