### ISSUE TITLE
1.21.1 NeoForge: BlockableEventLoop/FATAL // IllegalStateException crash

### ISSUE THREAD

**Issue by Daltaxy** [Potion-Studios/Oh-The-Biomes-Weve-Gone#126] opened 2024-09-24 14:31 UTC
Hello

After loading in, I use a Corail Tombstone's enchanted key to tp to my death spot. I pick up my stuff; a few seconds later the world freezes (can still move and break stuff but nothing drops, mobs are frozen)
log mentions an issue with the `deep_warm _ocean` and `lush_stacks`
pretty ironic that my favourite biome is the lush stacks

latest.log: https://mclo.gs/yynEE8Q
debug.log: https://mclo.gs/iUamIye
no crash report since the world froze instead

NeoForge loader 21.1.61
1.21.1
Oh-The-Biomes-Weve-Gone-NeoForge-2.1.0-Beta.jar

has to be linked with today's update of course, which was meant to fix another conflict with a vanilla biome as I saw from another issue? #119

**Comment by VaporeonScripts** [comment] 2024-09-24 16:34
got same issue xD

**Comment by Daltaxy** [comment] 2024-09-24 16:39
> got same issue xD

what mods do you have? maybe we can narrow it down?
maybe post your log too

**Comment by JT122406** [comment] 2024-09-24 17:23
William Wyther's Overhauled World is the cause, working on figuring out more now

**Comment by JT122406** [comment] 2024-09-24 17:27
Feature 'minecraft:seagrass_simple'
  must be before 'minecraft:sea_pickle' (defined in 'minecraft:deep_lukewarm_ocean' at index 10, 11)
  must be before 'minecraft:seagrass_normal' (defined in 'biomeswevegone:lush_stacks' at index 10, 11)
  must be before 'minecraft:seagrass_simple' (defined in 'minecraft:ocean' at index 8, 9)

**Comment by JT122406** [comment] 2024-09-24 17:28
Idk how this is possible because this change is what fixed compat with williams EE

**Comment by JT122406** [comment] 2024-09-24 17:49
Going to link this issue:
https://github.com/Cristelknight999/Expanded-Ecosphere/issues/107

**Comment by VaporeonScripts** [comment] 2024-09-24 17:57
> William Wyther's Overhauled World is the cause, working on figuring out more now

would expanded echosphere work? instead of using wwoo?

**Comment by JT122406** [comment] 2024-09-24 18:12
If you read that link you can see what’s happening

**Comment by VaporeonScripts** [comment] 2024-09-24 18:28
nvm,tried latest bwg and ee, still not working,ima just wait for a patch

**Comment by JT122406** [comment] 2024-09-24 19:09
> nvm,tried latest bwg and ee, still not working,ima just wait for a patch
like without wwoo?

**Comment by JT122406** [comment] 2024-09-24 19:22
![image](https://github.com/user-attachments/assets/d71dadd0-dae0-4be8-93a2-51ab2f4f7ba0)

**Comment by VaporeonScripts** [comment] 2024-09-24 20:04
i tried generating a world with bwg and expanded echosphere, without WWOO, it got stuck but no cycler error from console, might be a coincidence, ima just wait for the new patch ig

**Comment by VaporeonScripts** [comment] 2024-09-30 15:54
did this error get fixed?

**Comment by JT122406** [comment] 2024-09-30 15:57
Not yet

**Comment by VaporeonScripts** [comment] 2024-09-30 16:13
alright

**Comment by Daltaxy** [comment] 2024-09-30 17:08
> Not yet

weird cause nothing happens at the spot i was  crashing at anymore. thought it was fixed, especially following the recent update

**Comment by VaporeonScripts** [comment] 2024-09-30 17:13
![image](https://github.com/user-attachments/assets/57533ee8-bf5a-4aff-b540-a943374c6782)
noticed i just got this thing on my console lel

**Comment by Daltaxy** [comment] 2024-09-30 17:19
> > Not yet
> 
> weird cause nothing happens at the spot i was crashing at anymore. thought it was fixed, especially following the recent update

nevermind I just crashed lol

**Comment by VaporeonScripts** [comment] 2024-09-30 17:24
lmfao

**Comment by VaporeonScripts** [comment] 2024-10-07 19:40
2.1.2 fixed it or nah?

**Comment by Daltaxy** [comment] 2024-10-07 19:52
> 2.1.2 fixed it or nah?

![image](https://github.com/user-attachments/assets/165092db-49d9-42ab-b719-044d78ac4f39)

**Comment by VaporeonScripts** [comment] 2024-10-07 20:03
Alright,ty

**Comment by CorgiTaco** [comment] 2024-10-07 20:31
I'll probably port up feature recycler to be a bandaid fix for this

**Closed as completed** 2024-10-16 02:47 UTC
Labels: Incompatibility, Feature Cycle
