### ISSUE TITLE
Crash when a Firecracker Tree is ULTIMINED

### ISSUE THREAD

**Issue by HaizUber** [Potion-Studios/Oh-The-Biomes-Weve-Gone#69] opened 2024-08-08 13:12 UTC
Minecraft 1.20.1

Neoforge 47.1.106

Oh The Biomes We've Gone 1.0.4-BETA-FORGE

FTB Ultimine 2001.1.5

Steps to reproduce:
- Go to a Firecracker Chaparral
- Ultimine the oak log of a Firecracker tree (the small ones that have the firecracker leaves)
![image](https://github.com/user-attachments/assets/b655da1d-1eff-42f7-8d20-ac01c5f44dcb)
-Crash

latest.log: https://gist.github.com/HaizUber/0949713bb5d143fed2e38544c679671b

crashlog: https://gist.github.com/HaizUber/b0cf597903fa8c0e0bbca68a80a1f8b5

**Comment by HaizUber** [comment] 2024-08-08 13:14
[latest.log](https://github.com/user-attachments/files/16548515/latest.log)

seems like github gist cut some parts of the latest.log heres the file itself

**Comment by LordofDorknes** [comment] 2024-08-08 20:06
Looks like issue #56. You're on beta 1.0.4 which is still affected by that. Does it still happen if you update the mod to the 1.0.6 beta released today? It's strange because I can't tell whether the firecracker tree has fruiting leaves, which were thought to be the ones causing the crash.

**Comment by LordofDorknes** [comment] 2024-08-08 20:26
Seems to be fixed in beta 1.0.6, as I can't reproduce it using the firecracker chaparral leaves there but I'm not running the full modlist you are - just the minimal BWG setup.

**Comment by HaizUber** [comment] 2024-08-09 05:06
Hello, I can confirm this has been fixed on BWG version 1.0.6-BETA-FORGE also fixed the ticking exception i've been getting on the skyris trees 

> Seems to be fixed in beta 1.0.6, as I can't reproduce it using the firecracker chaparral leaves there but I'm not running the full modlist you are - just the minimal BWG setup.

**Closed** 2024-08-09 05:06 UTC
