### ISSUE TITLE
crash in my modpack bellow is the log (Temp Solution: Use Feature Recycler)

### ISSUE THREAD

**Issue by Thunderrock424242** [Potion-Studios/Oh-The-Biomes-Weve-Gone#53] opened 2024-08-02 02:48 UTC
was loading up creating a new world stuck on 0% then crashed 
[latest.log](https://github.com/user-attachments/files/16464631/latest.log)

**Comment by Thunderrock424242** [comment] 2024-08-02 02:48
btw you can find the modlist in the log

**Comment by CorgiTaco** [comment] 2024-08-11 12:23
Temporary solution is to use: https://www.curseforge.com/minecraft/mc-mods/feature-recycler

**Comment by Apollounknowndev** [comment] 2024-08-12 01:33
Duplicate of #16, conflict with WWEE.

**Comment by JT122406** [comment] 2024-08-12 22:51
Follow on #16

**Closed by JT122406** 2024-08-12 22:51 UTC
Labels: Incompatibility, Low Priority, Feature Cycle
