### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by pibblepower** [Potion-Studios/Oh-The-Biomes-Weve-Gone#72] opened 2024-08-09 01:32 UTC
When I try to disable the bayou in the config, it still spawns in the world. I have some other biomes I've disabled, but the bayou is the only one that still spawns regardless.

**Comment by JT122406** [comment] 2024-08-09 15:00
Duplicate of #71 Follow along there

**Closed by JT122406** 2024-08-09 15:00 UTC
Labels: duplicate
