### ISSUE TITLE
Orchard leaves decaying causes the game to crash (I am using forge).

### ISSUE THREAD

**Issue by ForestMinecraft** [Potion-Studios/Oh-The-Biomes-Weve-Gone#58] opened 2024-08-03 18:26 UTC
The crash seems to be caused by a issue with loot table based on the crash report.

**Comment by LordofDorknes** [comment] 2024-08-03 21:45
Duplicate of #56

**Comment by JT122406** [comment] 2024-08-03 23:35
See #56

**Closed by JT122406** 2024-08-03 23:35 UTC
Labels: duplicate
